FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libxml2-dev libxslt-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# opsiyonel ama faydalı:
ENV PYTHONPATH=/app

# CMD kalabilir; compose'taki 'command' bunu override eder
CMD ["python", "-m", "src.etl.run_pipeline"]
